using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using DlhSoft.Windows.Controls;

namespace _002.NullableGanttChartItem
{
    /// <summary>
    /// Represents a predecessor item generating a dependency between another task and the current task, within the Predecessors property of an <see cref="T:DlhSoft.Windows.Controls.IGanttChartItem">IGanttChartItem</see> object.
    /// </summary>
    public interface ICustomPredecessorItem
    {
        /// <summary>
        /// Gets the task item that the dependent task item of the current predecessor item depends of.
        /// </summary>
        ICustomGanttChartItem Item
        {
            get;
        }

        /// <summary>
        /// Gets the dependency type of the dependency generated by the current predecessor item (FinishStart, i.e. finish to start, by default).
        /// </summary>
        DependencyType DependencyType
        {
            get;
        }

        /// <summary>
        /// Gets the lag of the dependency generated by the current predecessor item.
        /// </summary>
        TimeSpan Lag
        {
            get;
        }
    }
}
